"""initial schema

Revision ID: 88de488f5b0b
Revises: 
Create Date: 2026-04-24 14:58:38.933862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88de488f5b0b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SELF_EMPLOYED_VAT', 'SELF_EMPLOYED_NO_VAT', 'PAYE_SIDE_INCOME', name='userrole'), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('business_address', sa.Text(), nullable=True),
    sa.Column('gdpr_consent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', name='auditaction'), nullable=False),
    sa.Column('diff', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_entity_id', 'audit_logs', ['entity_id'], unique=False)
    op.create_index('ix_audit_logs_entity_type', 'audit_logs', ['entity_type'], unique=False)
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_table('bank_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('counterparty', sa.String(length=255), nullable=True),
    sa.Column('reconciliation_status', sa.Enum('UNMATCHED', 'MATCHED', 'IGNORED', name='reconciliationstatus'), nullable=False),
    sa.Column('reconciled_with_type', sa.Enum('INVOICE', 'EXPENSE', name='reconciledwithtype'), nullable=True),
    sa.Column('reconciled_with_id', sa.String(length=36), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.Column('is_immutable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bank_transactions_date', 'bank_transactions', ['date'], unique=False)
    op.create_index('ix_bank_transactions_reconciliation_status', 'bank_transactions', ['reconciliation_status'], unique=False)
    op.create_index('ix_bank_transactions_user_id', 'bank_transactions', ['user_id'], unique=False)
    op.create_index('ix_bank_transactions_user_id_created_at', 'bank_transactions', ['user_id', 'created_at'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customers_user_id', 'customers', ['user_id'], unique=False)
    op.create_index('ix_customers_user_id_created_at', 'customers', ['user_id', 'created_at'], unique=False)
    op.create_table('tax_summaries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('summary_type', sa.Enum('ANNUAL', 'VAT3', 'RTD', name='taxsummarytype'), nullable=False),
    sa.Column('total_income', sa.Float(), nullable=False),
    sa.Column('total_expenses', sa.Float(), nullable=False),
    sa.Column('vat_collected', sa.Float(), nullable=False),
    sa.Column('vat_reclaimable', sa.Float(), nullable=False),
    sa.Column('vat_due', sa.Float(), nullable=False),
    sa.Column('taxable_income', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEWED', 'LOCKED', name='taxsummarystatus'), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tax_summaries_period_end', 'tax_summaries', ['period_end'], unique=False)
    op.create_index('ix_tax_summaries_period_start', 'tax_summaries', ['period_start'], unique=False)
    op.create_index('ix_tax_summaries_summary_type', 'tax_summaries', ['summary_type'], unique=False)
    op.create_index('ix_tax_summaries_user_id', 'tax_summaries', ['user_id'], unique=False)
    op.create_table('inquiries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'COMPLETED', 'ARCHIVED', name='inquirystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inquiries_customer_id', 'inquiries', ['customer_id'], unique=False)
    op.create_index('ix_inquiries_status', 'inquiries', ['status'], unique=False)
    op.create_index('ix_inquiries_user_id', 'inquiries', ['user_id'], unique=False)
    op.create_index('ix_inquiries_user_id_created_at', 'inquiries', ['user_id', 'created_at'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('inquiry_id', sa.String(length=36), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('sequence_year', sa.Integer(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ISSUED', 'PAID', 'OVERDUE', 'CANCELLED', name='invoicestatus'), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('vat_rate', sa.Float(), nullable=False),
    sa.Column('vat_amount', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'invoice_number', name='uq_invoices_user_invoice_number'),
    sa.UniqueConstraint('user_id', 'sequence_year', 'sequence_number', name='uq_invoices_user_year_seq')
    )
    op.create_index('ix_invoices_customer_id', 'invoices', ['customer_id'], unique=False)
    op.create_index('ix_invoices_inquiry_id', 'invoices', ['inquiry_id'], unique=False)
    op.create_index('ix_invoices_user_id', 'invoices', ['user_id'], unique=False)
    op.create_index('ix_invoices_user_id_created_at', 'invoices', ['user_id', 'created_at'], unique=False)
    op.create_table('receipts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('inquiry_id', sa.String(length=36), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('ocr_raw_text', sa.Text(), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('ocr_status', sa.Enum('PENDING', 'OK', 'FAILED', name='ocrstatus'), nullable=False),
    sa.Column('merchant', sa.String(length=255), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('vat_amount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_receipts_date', 'receipts', ['date'], unique=False)
    op.create_index('ix_receipts_inquiry_id', 'receipts', ['inquiry_id'], unique=False)
    op.create_index('ix_receipts_user_id', 'receipts', ['user_id'], unique=False)
    op.create_index('ix_receipts_user_id_created_at', 'receipts', ['user_id', 'created_at'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('receipt_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('inquiry_id', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('vat_amount', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ml_suggested_category', sa.String(length=255), nullable=True),
    sa.Column('ml_confidence', sa.Float(), nullable=True),
    sa.Column('user_confirmed_category', sa.String(length=255), nullable=True),
    sa.Column('is_vat_reclaimable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiries.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_id')
    )
    op.create_index('ix_expenses_category', 'expenses', ['category'], unique=False)
    op.create_index('ix_expenses_inquiry_id', 'expenses', ['inquiry_id'], unique=False)
    op.create_index('ix_expenses_receipt_id', 'expenses', ['receipt_id'], unique=False)
    op.create_index('ix_expenses_user_id', 'expenses', ['user_id'], unique=False)
    op.create_index('ix_expenses_user_id_created_at', 'expenses', ['user_id', 'created_at'], unique=False)
    op.create_table('invoice_line_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('vat_rate', sa.Float(), nullable=False),
    sa.Column('line_total_net', sa.Float(), nullable=False),
    sa.Column('line_total_vat', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invoice_line_items_invoice_id', 'invoice_line_items', ['invoice_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['bank_transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payments_invoice_id', 'payments', ['invoice_id'], unique=False)
    op.create_index('ix_payments_payment_date', 'payments', ['payment_date'], unique=False)
    op.create_index('ix_payments_transaction_id', 'payments', ['transaction_id'], unique=False)
    op.create_index('ix_payments_user_id', 'payments', ['user_id'], unique=False)
    op.create_index('ix_payments_user_id_created_at', 'payments', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payments_user_id_created_at', table_name='payments')
    op.drop_index('ix_payments_user_id', table_name='payments')
    op.drop_index('ix_payments_transaction_id', table_name='payments')
    op.drop_index('ix_payments_payment_date', table_name='payments')
    op.drop_index('ix_payments_invoice_id', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_invoice_line_items_invoice_id', table_name='invoice_line_items')
    op.drop_table('invoice_line_items')
    op.drop_index('ix_expenses_user_id_created_at', table_name='expenses')
    op.drop_index('ix_expenses_user_id', table_name='expenses')
    op.drop_index('ix_expenses_receipt_id', table_name='expenses')
    op.drop_index('ix_expenses_inquiry_id', table_name='expenses')
    op.drop_index('ix_expenses_category', table_name='expenses')
    op.drop_table('expenses')
    op.drop_index('ix_receipts_user_id_created_at', table_name='receipts')
    op.drop_index('ix_receipts_user_id', table_name='receipts')
    op.drop_index('ix_receipts_inquiry_id', table_name='receipts')
    op.drop_index('ix_receipts_date', table_name='receipts')
    op.drop_table('receipts')
    op.drop_index('ix_invoices_user_id_created_at', table_name='invoices')
    op.drop_index('ix_invoices_user_id', table_name='invoices')
    op.drop_index('ix_invoices_inquiry_id', table_name='invoices')
    op.drop_index('ix_invoices_customer_id', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('ix_inquiries_user_id_created_at', table_name='inquiries')
    op.drop_index('ix_inquiries_user_id', table_name='inquiries')
    op.drop_index('ix_inquiries_status', table_name='inquiries')
    op.drop_index('ix_inquiries_customer_id', table_name='inquiries')
    op.drop_table('inquiries')
    op.drop_index('ix_tax_summaries_user_id', table_name='tax_summaries')
    op.drop_index('ix_tax_summaries_summary_type', table_name='tax_summaries')
    op.drop_index('ix_tax_summaries_period_start', table_name='tax_summaries')
    op.drop_index('ix_tax_summaries_period_end', table_name='tax_summaries')
    op.drop_table('tax_summaries')
    op.drop_index('ix_customers_user_id_created_at', table_name='customers')
    op.drop_index('ix_customers_user_id', table_name='customers')
    op.drop_table('customers')
    op.drop_index('ix_bank_transactions_user_id_created_at', table_name='bank_transactions')
    op.drop_index('ix_bank_transactions_user_id', table_name='bank_transactions')
    op.drop_index('ix_bank_transactions_reconciliation_status', table_name='bank_transactions')
    op.drop_index('ix_bank_transactions_date', table_name='bank_transactions')
    op.drop_table('bank_transactions')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity_type', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity_id', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
